#!/bin/sh

if [ "$(id -u)" -eq 0 ]; then
    echo If you want to run me with sudo, delete the next line.
    echo Fair warning, I also install python stuff
    exit
fi

python3 -m pip install --user xmltodict
sudo apt install qemu
